name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gperf ccache dfu-util
          pip install west

      - name: Initialize West and Update
        run: |
          west init -l app/
          west update
          west zephyr-export

      - name: Build Firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DZMK_CONFIG=$(pwd)/config -DSHIELD=reviung41 -DKEYMAP=default
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
