name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache West Modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ hashFiles('zmk/zmk/app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Initialize West Workspace
        run: west init -l zmk/zmk/app

      - name: Update West Modules
        run: west update

      - name: Export Zephyr CMake Package
        run: west zephyr-export

      - name: Build Firmware
        run: |
          west build -s zmk/zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=$(pwd)/config -DSHIELD=reviung41 -DKEYMAP=default
          cp build/zephyr/zmk.uf2 build/zephyr/nice_nano_v2-reviung41.uf2

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nice_nano_v2-reviung41-default
          path: build/zephyr/nice_nano_v2-reviung41.uf2
